spring.datasource.url = jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGNAME:mydb}
jakarta.persistence.jdbc.url = jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGNAME:mydb} 
spring.datasource.username = ${PGUSER:db}
spring.datasource.password = ${PGPASSWORD:12345}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto = update
